services:
  prometheus:
    image: prom/prometheus:v3.5.0
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  node-exporter:
    image: prom/node-exporter:v1.9.1
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana:12.1.1
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
