sonar.projectKey=devops-task-api
sonar.projectName=DevOps Task API
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12
sonar.exclusions=**/__pycache__/**,**/.pytest_cache/**
sonar.python.coverage.reportPaths=coverage.xml
